### ISSUE TITLE
Vibrant Alloy Recipe creating Energetic Alloy instead in Arc Furnace

### ISSUE THREAD

**Issue by Taraxus** [Haggle1996/RevolutionPack#262]
If Ender Pearl Powder is put in with Energetic Alloy ingredients, it is ignored and the furnace produces Energetic Alloy instead.

**Comment by Taraxus** [comment]
BluSunrize/ImmersiveEngineering/issues/843

**Comment by Haggle1996** [comment]
This should be fixed in the next update.

**Comment by ghost** [comment]
Today, with the version 2.4.0.0, the recipe for the Vibrant Alloy is not fixed :/
